<?php

namespace App\Support;

class AttendanceRecordSource
{
    public const MANUAL = 'manual';

    public const SYSTEM = 'system';

    public const REASON_SESSION_EXPIRED = 'Session Expired Without Attendance';

    public static function label(?string $source, bool $autoGenerated = false): string
    {
        if ($autoGenerated || $source === self::SYSTEM) {
            return 'System Generated';
        }

        return 'Manual Attendance';
    }

    public static function portalLabel(bool $faceVerified, bool $geoVerified): string
    {
        if ($faceVerified && $geoVerified) {
            return 'Teacher Portal (Face + Geo)';
        }

        if ($faceVerified) {
            return 'Teacher Portal (Face)';
        }

        if ($geoVerified) {
            return 'Teacher Portal (Geo)';
        }

        return 'Teacher Portal';
    }
}
